/**
 * Certification run (docs/05-suppliers.md): executes the shared contract
 * suite and writes docs/certification/tbo.md via the supplier-sdk report
 * formatter.
 *
 *   pnpm --filter @jenova/adapter-hotel-tbo certify         # recorded only
 *   TBO_CONTRACT_LIVE=1 pnpm --filter … certify             # recorded + ONE live run
 *
 * The live run books and cancels one real sandbox reservation — run it
 * deliberately, never in CI, and never repeatedly.
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  formatCertificationReport,
  type CertificationCheck,
  type CertificationCheckStatus,
} from "@jenova/supplier-sdk/testing";
import { loadRepoEnv } from "./env";

const PACKAGE_DIR = fileURLToPath(new URL("..", import.meta.url));
const REPO_ROOT = fileURLToPath(new URL("../../../../..", import.meta.url));

interface VitestAssertion {
  ancestorTitles: string[];
  title: string;
  status: string;
  failureMessages?: string[];
}

interface VitestJsonReport {
  testResults: { assertionResults: VitestAssertion[] }[];
}

function runSuite(live: boolean): CertificationCheck[] {
  const outFile = join(mkdtempSync(join(tmpdir(), "tbo-cert-")), "results.json");
  const env = { ...process.env, ...(live ? { TBO_CONTRACT_LIVE: "1" } : {}) };
  if (!live) {
    delete env["TBO_CONTRACT_LIVE"];
  }
  const result = spawnSync(
    "pnpm",
    [
      "exec",
      "vitest",
      "run",
      "src/adapter.contract.test.ts",
      "--reporter=json",
      `--outputFile=${outFile}`,
    ],
    { cwd: PACKAGE_DIR, env, shell: true, stdio: ["ignore", "inherit", "inherit"] },
  );
  if (result.error) {
    throw result.error;
  }
  const report = JSON.parse(readFileSync(outFile, "utf8")) as VitestJsonReport;
  return report.testResults.flatMap((file) =>
    file.assertionResults.map((assertion) => toCheck(assertion)),
  );
}

function toCheck(assertion: VitestAssertion): CertificationCheck {
  const inLifecycle = assertion.ancestorTitles.some((t) => t.includes("lifecycle happy path"));
  const kindMatch =
    /SupplierError\((\w+)\)/.exec(assertion.title) ??
    /record this scenario first: (\w+)/.exec(assertion.title);
  const id = inLifecycle
    ? `lifecycle.${assertion.title.split(" ")[0] ?? "step"}`
    : `error.${kindMatch?.[1] ?? assertion.title.split(" ")[0] ?? "check"}`;
  const status = mapStatus(assertion.status);
  const failure = assertion.failureMessages?.[0]?.split("\n")[0];
  return {
    id,
    title: assertion.title,
    status,
    ...(failure === undefined ? {} : { detail: failure }),
  };
}

function mapStatus(status: string): CertificationCheckStatus {
  switch (status) {
    case "passed":
      return "passed";
    case "failed":
      return "failed";
    case "todo":
    case "pending":
      return "todo";
    default:
      return "skipped";
  }
}

const live = process.env["TBO_CONTRACT_LIVE"] === "1";
loadRepoEnv();

const sections: string[] = [
  "<!-- Generated by packages/adapters/hotel/tbo/tools/certify.ts — do not edit by hand. -->",
  "",
];

console.log("running contract suite on recordings…");
const recordedChecks = runSuite(false);
const recordedFailed = recordedChecks.some((check) => check.status === "failed");
sections.push(
  formatCertificationReport(
    {
      supplierCode: "tbo",
      environment: "sandbox",
      mode: "recorded",
      ranAtUtc: new Date().toISOString(),
    },
    recordedChecks,
  ),
);

let liveFailed = false;
if (live) {
  console.log("running contract suite LIVE against the TBO sandbox…");
  const liveChecks = runSuite(true);
  liveFailed = liveChecks.some((check) => check.status === "failed");
  sections.push(
    formatCertificationReport(
      {
        supplierCode: "tbo",
        environment: "sandbox",
        mode: "live",
        ranAtUtc: new Date().toISOString(),
      },
      liveChecks,
    ),
  );
} else {
  sections.push(
    "_No live section in this run: set TBO_CONTRACT_LIVE=1 (with the TBO block filled in .env) for the pre-certification live run._\n",
  );
}

const outPath = join(REPO_ROOT, "docs", "certification", "tbo.md");
mkdirSync(join(REPO_ROOT, "docs", "certification"), { recursive: true });
writeFileSync(outPath, sections.join("\n"), "utf8");
console.log(`wrote ${outPath}`);
if (recordedFailed || liveFailed) {
  process.exitCode = 1;
}
